# Generated by Django 4.0.3 on 2022-07-16 15:13

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=100)),
                ('tutorial_body', models.TextField()),
                ('tutorial_video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
